<template><view class="page">
<view class="hero" :style="{backgroundColor:theme.primaryColor}"><view class="hero-content"><text class="hero-name">{{shop.shortName||shop.name}}</text><text class="hero-desc">{{shop.description}}</text></view></view>
<view class="banner" @tap="goProducts"><text class="banner-icon">🎉</text><text class="banner-text">新人首单立减 ¥5 · 满 ¥30 减 ¥8</text><text class="banner-arrow">></text></view>
<view class="actions"><view class="act" @tap="goProducts"><view class="act-icon bg1">📋</view><text>全部菜品</text></view>
<view class="act" @tap="goCart"><view class="act-icon bg2">🛒</view><text>点餐车</text></view>
<view class="act" @tap="goOrders"><view class="act-icon bg3">📦</view><text>订单</text></view>
<view class="act" @tap="callShop"><view class="act-icon bg4">📞</view><text>联系店家</text></view></view>
<view class="section"><text class="stitle">🔥 招牌推荐</text><scroll-view scroll-x class="dish-scroll">
<view class="dish-card" v-for="i in 4" :key="i" @tap="goProducts"><view class="dish-img">🍽️</view>
<text class="dish-name">{{['鱼香肉丝','宫保鸡丁','酸辣土豆丝','红烧排骨'][i-1]}}</text>
<text class="dish-price">¥{{[28,22,18,38][i-1]}}</text></view></scroll-view></view>
<view class="section" v-if="shop.phone"><text class="sinfo">📍 {{shop.address||''}} · 📞 {{shop.phone||''}}</text></view>
</view></template>
<script>import config from '../../school.config.json';export default{data(){return{shop:config.shop,theme:config.shop.theme}},methods:{goProducts(){uni.switchTab({url:'/pages/products/products'})},goCart(){uni.switchTab({url:'/pages/cart/cart'})},goOrders(){uni.navigateTo({url:'/pages/orders/orders'})},callShop(){uni.makePhoneCall({phoneNumber:this.shop.phone})}}}</script>
<style scoped>.page{background:#f5f5f5;min-height:100vh}.hero{padding:50rpx 30rpx 40rpx;color:#fff;text-align:center}.hero-name{font-size:44rpx;font-weight:800}.hero-desc{font-size:24rpx;opacity:.85;margin-top:8rpx}.banner{display:flex;align-items:center;margin:20rpx 24rpx;padding:20rpx;background:linear-gradient(135deg,#ff6b35,#ff8c5a);border-radius:14rpx;color:#fff}.banner-icon{margin-right:12rpx;font-size:32rpx}.banner-text{flex:1;font-size:26rpx;font-weight:500}.actions{display:flex;margin:20rpx 24rpx;background:#fff;border-radius:16rpx;padding:28rpx 0}.act{flex:1;text-align:center;font-size:24rpx}.act-icon{width:96rpx;height:96rpx;border-radius:24rpx;margin:0 auto 10rpx;display:flex;align-items:center;justify-content:center;font-size:44rpx}.bg1{background:#fff3e0}.bg2{background:#e8f5e9}.bg3{background:#e3f2fd}.bg4{background:#fce4ec}.section{margin:20rpx 24rpx;padding:20rpx;background:#fff;border-radius:12rpx}.stitle{font-size:30rpx;font-weight:700;display:block;margin-bottom:16rpx}.dish-scroll{white-space:nowrap}.dish-card{display:inline-block;width:200rpx;margin-right:16rpx;background:#fafafa;border-radius:14rpx;padding:16rpx;position:relative}.dish-img{font-size:64rpx;text-align:center;padding:20rpx}.dish-name{font-size:26rpx;font-weight:600;display:block;margin-top:6rpx}.dish-price{font-size:26rpx;color:#ff4d4f;font-weight:700;display:block;margin-top:4rpx}.sinfo{font-size:26rpx;color:#666}</style>
