<template><view class="page">
<view v-if="cartItems.length">
<view class="cart-item" v-for="(c,i) in cartItems" :key="i"><text class="ci-name">{{c.name}}</text>
<view class="ci-ctrl"><view class="qty-btn" @tap="changeQty(i,-1)">-</view><text class="ci-qty">{{c.qty||1}}</text><view class="qty-btn" @tap="changeQty(i,1)">+</view></view>
<text class="ci-price">¥{{c.price*(c.qty||1)}}</text></view>
<view class="mode-bar"><text class="mode-title">取餐方式</text><view class="mode-opt" :class="{active:pickupMode==='pickup'}" @tap="pickupMode='pickup'">🏪 到店自取</view><view class="mode-opt" :class="{active:pickupMode==='delivery'}" @tap="pickupMode='delivery'">🛵 外卖配送</view></view>
<view class="addr-inp" v-if="pickupMode==='delivery'"><input placeholder="请输入配送地址" v-model="address"/></view>
<view class="time-bar"><text class="mode-title">预计 {{pickupMode==='pickup'?'取餐':'送达'}}时间：约30分钟</text></view>
<view class="total-bar"><text>合计</text><text class="total-price">¥{{totalPrice}}</text></view>
<button class="btn" :style="{background:theme.primaryColor}" @tap="submitOrder">确认下单</button></view>
<view class="empty" v-else>点餐车是空的</view></view></template>
<script>import config from '../../school.config.json';export default{data(){return{theme:config.shop.theme,cartItems:[],pickupMode:'pickup',address:''}},computed:{totalPrice(){return this.cartItems.reduce(function(s,c){return s+c.price*(c.qty||1)},0)}},onShow(){var app=getApp();this.cartItems=app.globalData.cart||[]},methods:{changeQty(i,d){var c=this.cartItems[i];c.qty=(c.qty||1)+d;if(c.qty<1){this.cartItems.splice(i,1)}getApp().globalData.cart=this.cartItems},submitOrder(){var t=this.pickupMode==='pickup'?'已下单，到店取餐':'已下单，配送到 '+this.address;uni.showToast({title:t,icon:'success'});getApp().globalData.cart=[];this.cartItems=[];setTimeout(function(){uni.switchTab({url:'/pages/orders/orders'})},1500)}}}</script>
<style scoped>.page{padding:20rpx;padding-bottom:200rpx}.cart-item{background:#fff;border-radius:12rpx;padding:20rpx;margin-bottom:12rpx;display:flex;align-items:center;gap:14rpx}.ci-name{flex:1;font-size:28rpx;font-weight:500}.ci-ctrl{display:flex;align-items:center;gap:12rpx}.qty-btn{width:48rpx;height:48rpx;border-radius:24rpx;background:#f0f0f0;text-align:center;line-height:48rpx;font-size:28rpx;font-weight:600}.ci-qty{font-size:28rpx;font-weight:600;min-width:40rpx;text-align:center}.ci-price{font-size:26rpx;color:#ff4d4f;font-weight:600;min-width:100rpx;text-align:right}.mode-bar{padding:20rpx;background:#fff;border-radius:12rpx;margin:16rpx 0}.mode-title{font-size:28rpx;font-weight:600;display:block;margin-bottom:12rpx}.mode-opt{display:inline-block;padding:12rpx 24rpx;border:2rpx solid #eee;border-radius:10rpx;margin-right:16rpx;font-size:26rpx}.mode-opt.active{border-color:#1890ff;background:#f0f5ff}.addr-inp input{width:100%;padding:16rpx;border:1px solid #eee;border-radius:8rpx;font-size:28rpx;margin-bottom:12rpx}.time-bar{padding:16rpx 0;font-size:26rpx;color:#666}.total-bar{display:flex;justify-content:space-between;padding:20rpx;font-size:30rpx;font-weight:600}.total-price{color:#ff4d4f}.btn{width:100%;color:#fff;border-radius:50rpx;height:88rpx;line-height:88rpx;font-size:30rpx;font-weight:600}.empty{text-align:center;color:#999;padding:100rpx 0;font-size:28rpx}</style>
