<template><view class="page">
<view class="hero" :style="{backgroundColor:theme.primaryColor}"><view class="hero-content"><text class="hero-name">{{shop.shortName||shop.name}}</text><text class="hero-desc">{{shop.description}}</text></view></view>
<view class="banner"><text class="banner-icon">🎁</text><text class="banner-text">新客首次体验5折 · 闺蜜同行一人免单</text></view>
<view class="actions"><view class="act" @tap="goProducts"><view class="act-icon bg1">💅</view><text>服务项目</text></view>
<view class="act" @tap="goBooking"><view class="act-icon bg2">📅</view><text>预约到店</text></view>
<view class="act" @tap="goOrders"><view class="act-icon bg3">📋</view><text>我的订单</text></view>
<view class="act" @tap="callShop"><view class="act-icon bg4">📞</view><text>联系店家</text></view></view>
<view class="section"><text class="stitle">💎 热门服务</text><view class="svc-list"><view class="svc-row" @tap="goBooking"><text>法式美甲</text><text class="svc-p">¥168</text><text class="svc-t">热销</text></view>
<view class="svc-row" @tap="goBooking"><text>韩式纹眉</text><text class="svc-p">¥288</text><text class="svc-t">推荐</text></view>
<view class="svc-row" @tap="goBooking"><text>面部清洁护理</text><text class="svc-p">¥128</text><text class="svc-t"></text></view></view></view>
<view class="section" v-if="shop.address"><text class="stitle">📍 {{shop.address}}</text></view>
</view></template>
<script>import config from '../../school.config.json';export default{data(){return{shop:config.shop,theme:config.shop.theme}},methods:{goProducts(){uni.navigateTo({url:'/pages/products/products'})},goBooking(){uni.navigateTo({url:'/pages/booking/booking'})},goOrders(){uni.switchTab({url:'/pages/orders/orders'})},goCart(){uni.switchTab({url:'/pages/cart/cart'})},callShop(){uni.makePhoneCall({phoneNumber:this.shop.phone})}}}</script>
<style scoped>.page{background:#f5f5f5;min-height:100vh}.hero{padding:50rpx 30rpx 40rpx;color:#fff;text-align:center}.hero-name{font-size:44rpx;font-weight:800}.hero-desc{font-size:24rpx;opacity:.85;margin-top:8rpx}.banner{display:flex;align-items:center;margin:20rpx 24rpx;padding:20rpx;background:linear-gradient(135deg,#e91e8c,#f06292);border-radius:14rpx;color:#fff}.banner-icon{margin-right:12rpx;font-size:32rpx}.banner-text{flex:1;font-size:26rpx;font-weight:500}.actions{display:flex;margin:20rpx 24rpx;background:#fff;border-radius:16rpx;padding:28rpx 0}.act{flex:1;text-align:center;font-size:24rpx}.act-icon{width:96rpx;height:96rpx;border-radius:24rpx;margin:0 auto 10rpx;display:flex;align-items:center;justify-content:center;font-size:44rpx}.bg1{background:#fce4ec}.bg2{background:#e8f5e9}.bg3{background:#e3f2fd}.bg4{background:#fff3e0}.section{margin:20rpx 24rpx;padding:20rpx;background:#fff;border-radius:12rpx}.stitle{font-size:30rpx;font-weight:700;display:block;margin-bottom:16rpx}.svc-row{display:flex;align-items:center;padding:16rpx 0;border-bottom:1rpx solid #f0f0f0;font-size:28rpx}.svc-p{margin-left:auto;color:#ff4d4f;font-weight:700;margin-right:12rpx}.svc-t{font-size:20rpx;background:#ff4d4f;color:#fff;padding:2rpx 8rpx;border-radius:6rpx}</style>
