<template><view class="page">
<view class="hero" :style="{backgroundColor:theme.primaryColor}"><view class="hero-content"><text class="hero-name">{{shop.shortName||shop.name}}</text><text class="hero-desc">{{shop.description}}</text></view></view>
<view class="banner"><text class="banner-icon">🎓</text><text class="banner-text">试听课免费预约 · 报名立减 ¥200</text></view>
<view class="actions"><view class="act" @tap="goProducts"><view class="act-icon bg1">📚</view><text>全部课程</text></view>
<view class="act" @tap="goBooking"><view class="act-icon bg2">🎤</view><text>试听预约</text></view>
<view class="act" @tap="goOrders"><view class="act-icon bg3">📋</view><text>我的课程</text></view>
<view class="act" @tap="callShop"><view class="act-icon bg4">📞</view><text>咨询</text></view></view>
<view class="section"><text class="stitle">⭐ 热门课程</text>
<view class="course-card" v-for="(c,i) in courses" :key="i" @tap="goBooking"><text class="cname">{{c.name}}</text><text class="cinfo">{{c.teacher}} · {{c.age}} · {{c.hours}}课时</text><text class="cprice">¥{{c.price}}</text><text class="ctag" v-if="c.tag">{{c.tag}}</text></view></view>
<view class="section"><text class="stitle">💬 学员好评</text><view class="review"><text>"老师很耐心，孩子进步明显" — 李妈妈</text></view><view class="review"><text>"试听课体验很好，当场报了名" — 王爸爸</text></view></view>
</view></template>
<script>import config from '../../school.config.json';export default{data(){return{shop:config.shop,theme:config.shop.theme,courses:[{name:'少儿英语启蒙班',teacher:'张老师',age:'4-6岁',hours:32,price:2800,tag:'热招'},{name:'小学数学思维',teacher:'李老师',age:'7-9岁',hours:24,price:2200,tag:'推荐'},{name:'初中物理实验',teacher:'王老师',age:'12-15岁',hours:16,price:1800,tag:''}]}},methods:{goProducts(){uni.navigateTo({url:'/pages/products/products'})},goBooking(){uni.navigateTo({url:'/pages/booking/booking'})},goOrders(){uni.switchTab({url:'/pages/orders/orders'})},callShop(){uni.makePhoneCall({phoneNumber:this.shop.phone})}}}</script>
<style scoped>.page{background:#f5f5f5;min-height:100vh}.hero{padding:50rpx 30rpx 40rpx;color:#fff;text-align:center}.hero-name{font-size:44rpx;font-weight:800}.hero-desc{font-size:24rpx;opacity:.85;margin-top:8rpx}.banner{display:flex;align-items:center;margin:20rpx 24rpx;padding:20rpx;background:linear-gradient(135deg,#4caf50,#81c784);border-radius:14rpx;color:#fff}.banner-icon{margin-right:12rpx;font-size:32rpx}.banner-text{flex:1;font-size:26rpx;font-weight:500}.actions{display:flex;margin:20rpx 24rpx;background:#fff;border-radius:16rpx;padding:28rpx 0}.act{flex:1;text-align:center;font-size:24rpx}.act-icon{width:96rpx;height:96rpx;border-radius:24rpx;margin:0 auto 10rpx;display:flex;align-items:center;justify-content:center;font-size:44rpx}.bg1{background:#e8f5e9}.bg2{background:#fff3e0}.bg3{background:#e3f2fd}.bg4{background:#fce4ec}.section{margin:20rpx 24rpx;padding:20rpx;background:#fff;border-radius:12rpx}.stitle{font-size:30rpx;font-weight:700;display:block;margin-bottom:16rpx}.course-card{position:relative;padding:20rpx;border:1rpx solid #eee;border-radius:12rpx;margin-bottom:12rpx}.cname{font-size:30rpx;font-weight:600}.cinfo{font-size:24rpx;color:#999;display:block;margin-top:4rpx}.cprice{font-size:28rpx;color:#ff4d4f;font-weight:700;margin-top:8rpx}.ctag{position:absolute;top:20rpx;right:20rpx;background:#4caf50;color:#fff;font-size:20rpx;padding:4rpx 12rpx;border-radius:8rpx}.review{padding:16rpx 0;border-bottom:1rpx solid #f0f0f0;font-size:26rpx;color:#666}</style>
