<template><view class="page">
<view class="card"><text class="title">选择日期</text>
<view style="padding:10rpx 0;font-size:22rpx;color:#ff4d4f">平日¥188 周末¥268 节假日¥388</view>
<scroll-view scroll-x class="date-list"><view class="date-item" v-for="(d,i) in dates" :key="i" :class="{active:selDate===i}" @tap="selDate=i"><text class="week">{{d.weekday}}</text><text class="day">{{d.month}}/{{d.day}}</text></view></scroll-view></view>
<view class="card" v-if="selDate!==null"><text class="title">选择时段</text>
<view class="time-grid"><view class="time-btn" v-for="(t,i) in timeSlots" :key="i" :class="{active:selTime===i}" @tap="selTime=i"><text>{{t}}</text></view></view></view>
<view class="card" v-if="selTime!==null"><text class="title">填写信息</text>
<view class="card" v-if="selTime!==null"><text class="title">选择技师</text><view class="staff-grid"><view class="staff-btn" v-for="(s,si) in staffList" :key="si" :class="{active:selStaff===si}" @tap="selStaff=si">{{s}}</view></view></view>
<input class="inp" v-model="name" placeholder="姓名"/><input class="inp" v-model="phone" placeholder="手机号"/><input class="inp" v-model="remark" placeholder="备注（选填）"/></view>
<view class="submit" v-if="name&&phone"><button class="btn" :style="{background:theme.primaryColor}" @tap="submit">确认预约</button></view>
</view></template>
<script>import config from '../../school.config.json';export default{data(){return{theme:config.shop.theme,dates:[],selDate:null,selTime:null,timeSlots:['08:00-10:00','10:00-12:00','14:00-16:00','16:00-18:00'],name:'',phone:'',remark:''}},onLoad(){this.buildDates()},methods:{buildDates(){var s=this,wd=['周日','周一','周二','周三','周四','周五','周六'],ds=[];for(var i=0;i<7;i++){var t=new Date(Date.now()+i*86400000);ds.push({month:t.getMonth()+1,day:t.getDate(),weekday:wd[t.getDay()]})}s.dates=ds},submit(){uni.showToast({title:'预约成功！',icon:'success'});setTimeout(function(){uni.navigateBack()},1500)}}}</script>
staffList:["随意安排","金牌技师","资深技师","新锐技师"],selStaff:0,
<style scoped>.page{padding:20rpx;padding-bottom:200rpx}.card{background:#fff;border-radius:16rpx;padding:24rpx;margin-bottom:20rpx}.title{font-size:30rpx;font-weight:700;display:block;margin-bottom:16rpx}.date-list{white-space:nowrap}.date-item{display:inline-block;text-align:center;width:100rpx;padding:16rpx 0;border-radius:12rpx;margin-right:12rpx;border:2rpx solid #eee}.date-item.active{border-color:#1890ff;background:#f0f5ff}.week{font-size:22rpx;color:#999;display:block}.day{font-size:30rpx;font-weight:600;margin-top:6rpx;display:block}.time-grid{display:flex;flex-wrap:wrap;gap:16rpx}.time-btn{flex:0 0 calc(50% - 8rpx);text-align:center;padding:24rpx;border-radius:14rpx;border:2rpx solid #eee;font-size:28rpx}.time-btn.active{border-color:#1890ff;background:#f0f5ff}.inp{width:100%;padding:22rpx 0;border-bottom:1rpx solid #f0f0f0;font-size:28rpx}.btn{width:100%;color:#fff;border-radius:50rpx;height:92rpx;line-height:92rpx;font-size:32rpx}</style>
